system:
  host: 0.0.0.0
  port: 8080
  env: debug

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: gin
  log_level: dev

redis:
  host: 127.0.0.1
  port: 6379

logger:
  level: info
  prefix: "[gin_project]"
  director: log
  show_line: true
  log_in_console: true

aliyun_sms:
  access_key_id: "XXX"
  access_key_secret: "XXX"
  region_id: "cn-hangzhou"
  sign_name: "XXX"
  template_code: "XXX"