system:
  host: 0.0.0.0
  port: 8080
  env: debug

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: gin
  log_level: dev

redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  password: ""

zap:
  level: info
  format: console
  prefix: "[github.com/flipped-aurora/gin-vue-admin/server]"
  director: log
  show_line: true
  encode_level: LowercaseColorLevelEncoder
  stacktrace_key: stacktrace
  log_in_console: true

